server:
  port: 8080
spring:
  redis:
    host: 121.5.200.64
    port: 6379
    password: 123456
    timeout: 10000
    max-wait: -1
  datasource:
    #需要连接的本地数据库
    url: jdbc:mysql://121.5.200.64:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    #驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    username: root  #用户名
    password: wu123456  #密码
  # mq service
  rocketmq:
    name-server: 121.5.200.64:9876
    producer:
      group: my-mq-group
      send-message-timeout: 86400
      compress-message-body-threshold: 4096
      max-message-size: 4194304
      retry-times-when-send-async-failed: 0
      retry-next-server: true
      retry-times-when-send-failed: 2
logging:
  config: classpath:logback-spring.xml
mybatis:
  mapper-locations: classpath*:mapper/*.xml